/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { OpsReady, OpsReadyInterface } from "../OpsReady";

const _abi = [
  {
    inputs: [],
    name: "dedicatedMsgSender",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "ops",
    outputs: [
      {
        internalType: "contract IOps",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

export class OpsReady__factory {
  static readonly abi = _abi;
  static createInterface(): OpsReadyInterface {
    return new utils.Interface(_abi) as OpsReadyInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): OpsReady {
    return new Contract(address, _abi, signerOrProvider) as OpsReady;
  }
}
