/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, BytesLike, CallOverrides, PopulatedTransaction, Signer, utils } from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface IOpsProxyFactoryInterface extends utils.Interface {
  contractName: "IOpsProxyFactory";
  functions: {
    "getProxyOf(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "getProxyOf", values: [string]): string;

  decodeFunctionResult(functionFragment: "getProxyOf", data: BytesLike): Result;

  events: {};
}

export interface IOpsProxyFactory extends BaseContract {
  contractName: "IOpsProxyFactory";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: IOpsProxyFactoryInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    getProxyOf(account: string, overrides?: CallOverrides): Promise<[string, boolean]>;
  };

  getProxyOf(account: string, overrides?: CallOverrides): Promise<[string, boolean]>;

  callStatic: {
    getProxyOf(account: string, overrides?: CallOverrides): Promise<[string, boolean]>;
  };

  filters: {};

  estimateGas: {
    getProxyOf(account: string, overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    getProxyOf(account: string, overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
