/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { BaseContract, BigNumber, BytesLike, CallOverrides, PopulatedTransaction, Signer, utils } from "ethers";
import { FunctionFragment, Result } from "@ethersproject/abi";
import { Listener, Provider } from "@ethersproject/providers";
import { TypedEventFilter, TypedEvent, TypedListener, OnEvent } from "./common";

export interface OpsReadyInterface extends utils.Interface {
  contractName: "OpsReady";
  functions: {
    "dedicatedMsgSender()": FunctionFragment;
    "ops()": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "dedicatedMsgSender", values?: undefined): string;
  encodeFunctionData(functionFragment: "ops", values?: undefined): string;

  decodeFunctionResult(functionFragment: "dedicatedMsgSender", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "ops", data: BytesLike): Result;

  events: {};
}

export interface OpsReady extends BaseContract {
  contractName: "OpsReady";
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  interface: OpsReadyInterface;

  queryFilter<TEvent extends TypedEvent>(
    event: TypedEventFilter<TEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TEvent>>;

  listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>;
  listeners(eventName?: string): Array<Listener>;
  removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this;
  removeAllListeners(eventName?: string): this;
  off: OnEvent<this>;
  on: OnEvent<this>;
  once: OnEvent<this>;
  removeListener: OnEvent<this>;

  functions: {
    dedicatedMsgSender(overrides?: CallOverrides): Promise<[string]>;

    ops(overrides?: CallOverrides): Promise<[string]>;
  };

  dedicatedMsgSender(overrides?: CallOverrides): Promise<string>;

  ops(overrides?: CallOverrides): Promise<string>;

  callStatic: {
    dedicatedMsgSender(overrides?: CallOverrides): Promise<string>;

    ops(overrides?: CallOverrides): Promise<string>;
  };

  filters: {};

  estimateGas: {
    dedicatedMsgSender(overrides?: CallOverrides): Promise<BigNumber>;

    ops(overrides?: CallOverrides): Promise<BigNumber>;
  };

  populateTransaction: {
    dedicatedMsgSender(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    ops(overrides?: CallOverrides): Promise<PopulatedTransaction>;
  };
}
